name: face_antispoofing_vn_exp1.5_sample
annotation_path: data/sampled/face_antispoofing_vn_exp1.5_sample.csv
image_root: data/face_antispoofing_vn_cropped_sfas_exp1.5
source_dataset: face_antispoofing_vn_exp1.5
default_split: all
labels:
  live: live
  spoof: spoof
  unknown: unknown
