name: drivers_250_fn_exp2.7_sample
annotation_path: data/sampled/drivers_250_fn_exp2.7_sample.csv
image_root: data/drivers_250_fn_cropped_sfas_exp2.7
source_dataset: drivers_250_fn_exp2.7
default_split: all
labels:
  live: live
  spoof: spoof
  unknown: unknown
